### ISSUE TITLE
7.1.1. recommendation ?

### ISSUE THREAD

**Issue by bifurcation** [mlswg/mls-architecture#141]
_Comment by @paulwouters_

~~~ 
      *RECOMMENDATION:* Never use the unencrypted mode for group
      operations without using a secure channel for the transport layer.
~~~
Seems like a MUST NOT downgraded to RECOMMENDED ?

**Comment by bifurcation** [comment]
I would not make this a MUST NOT.  If you violate the recommendation, you end up in basically the same posture as TLS 1.2 -- the message content is are private, but the membership is known.  Clearly this shouldn't be the default, but might be acceptable in some cases.

**Comment by rohan-wire** [comment]
@paulwouters
This isn't a standards track or BCP document and the document was written to avoid normative language (there is no reference to RFC2119 and only one uppercase MUST, which I will write a PR to lowercase). Otherwise RECOMMENDATION would just be SHOULDs.

I agree with Richard that a MUST NOT would be overkill here if were using normative language.

**Comment by paulwouters** [comment]
fair enough, feel free to close
