### ISSUE TITLE
Recommendation for encrypted group operations

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#210]
> **RECOMMENDATION:** Prefer using encrypted group operation messages to avoid
> privacy issues related to non-encrypted signatures.

It seems like MIMI is converging on the opposite practice, so perhaps we should reconsider this.

**Comment by kkohbrok** [comment]
I'm a bit conflicted on this. Yes, if you use public messages, the DS can track group state, validate messages and assist clients. On the other hand, it leads to lots of metadata leakage if there is no additional mitigation on the application layer.

**Comment by ekr** [comment]
I don't disagree with you on the technical situation. I just think it's bad to have the main IETF effort that uses MLS do something different than this document recommends, so we should make them consistent.

**Comment by kkohbrok** [comment]
True. Looking at the context of the recommendation, I think we're okay removing it. The language around it is clear enough on the metadata aspect of private vs. public messages.

**Comment by ekr** [comment]
I agree that they should document them, so that we can determine whether they are sufficiently generic that this recommendation should be changed.

**Comment by ekr** [comment]
@rohan-wire we had a discussion about this in the meeting where I understood you to be saying you wanted to discuss in MIMI. As I understand it, however, MIMI still is using unencrypted handshake messages, so this issue is still extant.

**Comment by ekr** [comment]
@seanturner @grittygrease  I think we need the chairs to help drive this to conclusion.

**Comment by beurdouche** [comment]
I would much prefer the clients to encrypt group operations by default and for clients to contribute to maintaining a public tree in the server state by having specific encrypted messages to the server (sure that costs a bit of bandwidth). That would prevent other parties than the server to be able to reconstruct the public group and in particular the leafs if there is some kind of transport compromise.

**Comment by ekr** [comment]
I think this is a reasonable technical argument, but as I noted in the comment at the top of the issue, this is not what any current MIMI proposal says. Given that MIMI is the sole IETF WG making use of MLS, I don't think it makes sense for MLS to recommend something different than what MIMI is doing. So I think either people need to make the case to MIMI that group operations should be encrypted or this text needs to change.

**Comment by rohanmahy** [comment]
We had a discussion about using PrivateMessage for Commits in the MIMI design team. The result was unanimous that MIMI requires functionality that is only practical using PublicMessage. Raphael and Konrad have specific approaches to reduce the metadata seen by intermediaries in this case.

For the specific language, I recommend:
"RECOMMENDATION: Prefer using encrypted group operation messages to avoid
privacy issues related to non-encrypted signatures, unless group authorization or assisted joining by an intermediary are desired.

**Comment by ekr** [comment]
This seems way too strong, given that the use cases we are standardizing actually do not meet this recommendation. The idea here is to avoid the RFC 6919 "MUST (BUT WE KNOW YOU WON'T)" problem. The existing text is quite clear on the consequences of not using unencrypted operations, so I think it makes much more sense to simply strike this text.

**Comment by seanturner** [comment]
Will discuss at 2024-01-25 interim.

**Comment by ekr** [comment]
Unfortunately, I have a conflict for that.

**Comment by Bren2010** [comment]
Discussion at the interim can be generally summed up as:
- Agreement that encrypted group operations should be the first choice. Applications that don't encrypt operations should be able to articulate the reason why.
- Acknowledging that most deployed applications don't encrypt group operations (though some do). The reason most applications don't encrypt group operations, is that they can 1.) guarantee strong transport-layer security, 2.) don't care about leaking group membership to a central server, and 3.) want to use that central server to provide certain features.
  - These features include: small Welcome messages, small GroupInfo for external joiners, automated management of membership (removing inactive members, etc)
- Despite being well-represented, applications that meet criteria 1, 2, and 3 is actually quite a specific subset within the space of what MLS was designed to support!

**Comment by rohan-wire** [comment]
I don't think that captured the spirit of the discussion. I thought we agreed that we would discuss this choice in terms of the properties you gain or lose as a result. @Bren2010 you are portraying this decision as an efficiency decision but that is a secondary one. 

The vast majority of MLS implementations use PublicMessage for handshake messages, so I think it is a stretch to call encrypted handshakes the first choice.  There are two main reasons many implementations want to see Commits: to provide a place where authorized clients can a) fetch a GroupInfo for external joiners (especially when the other members of the group might be offline) and b) to enforce application and security policy. (To be blunt most applications expect strong data consistency, the implication being that a central entity needs to decide which commits are accepted and which are rejected. Making a sane judgement if a commit should be accepted is very difficult to do when the central entity does not even have an identity for the sender of the Commit.)

"MLS handshake messages can be sent encrypted (in an MLS PrivateMessage) or unencrypted (in an MLS PublicMessage). Applications may be designed such that intermediaries need to see handshake messages in order to enforce policy on which commits are allowed, and/or to provide MLS GroupInfo messages in a central location. If handshake messages are unencrypted, they absolutely need to be sent over a channel with strong transport encryption. Applications that use unencrypted handshake messages may take additional steps to reduce the amount of metadata that is exposed to the intermediary. Everything else being equal, using encrypted handshake messages provides stronger privacy properties than using unencrypted handshake messages."

**Comment by ekr** [comment]
I think @rohan-wire's text is generally good.

I would remove the word "absolutely" ahead of "need" as unnecessary.

**Comment by ekr** [comment]
I created PR #246 for this. @rohan-wire @beurdouche @Bren2010 PTAL
