### ISSUE TITLE
Compromise of group secrets

### ISSUE THREAD

**Issue by ekr** [mlswg/mls-architecture#214]
> If the adversary is active, the adversary can follow the protocol and perform
updates on behalf of the compromised party with no ability for an honest group
to recover message secrecy. However, MLS provides PCS against active adaptive
attackers through its Remove group operation. This means that, as long as other
members of the group are honest, the protocol will guarantee message secrecy for
all messages exchanged in the epochs after the compromised party has been
removed.

Up to the point where the client is no longer compromised and sends its own updates, right?

**Comment by kkohbrok** [comment]
I'm not sure if I understand correctly. 

In the scenario that I think the text is talking abouut, where the adversary (impersonating the compromised client) has sent one or more updates, the compromised client is essentially locked out of the group, because it doesn't have access to the key material freshly generated by the adversary as part of the updates. In particular, the compromised client can't send an update. At that point, a remove (maybe via an external commit by the compromised client) is necessary to fully evict the adversary from the group.

**Comment by papatiya** [comment]
Salam
